apiVersion: v1
kind: Pod
metadata:
  name: pod-db-sistema-noticias
  labels:
    app: pod-db-sistema-noticias
spec:
  containers:
    - name: container-db-sistema-noticias
      image: aluracursos/mysql-db:1
      ports:
        - containerPort: 3306
      envFrom:
        - configMapRef:
            name: configmap-pod-db-sistema-noticias