apiVersion: v1
kind: Service
metadata:
  name: src-httpd-clusterip
  labels:
    app: pod-httpd-example
spec:
  type: ClusterIP
  selector:
    app: pod-httpd-example
  ports: 
    - port: 9000
      targetPort: 80