apiVersion: v1
kind: Service
metadata:
  name: svc-nodeport-pod-web-portal-noticias
spec:
  type: NodePort
  selector:
    app: pod-web-portal-noticias
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001